title: Bonsai @ LMB 2020
description: Bonsai introduction at LMB 2020.
google_analytics:
theme: minima
baseurl: "/lmb-2020"

twitter_username: bonsai_rx
github_username:  neurogears

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - "**README.md"
